-- Usage: mcp__algocline__alc_pkg_test pkg=swarm_frame
local norm = require("swarm_frame.normalize")
local describe, it, expect = lust.describe, lust.it, lust.expect

describe("coerce_boolean", function()
    it("returns the value when it is true", function()
        expect(norm.coerce_boolean(true)).to.equal(true)
    end)
    it("returns the value when it is false", function()
        expect(norm.coerce_boolean(false)).to.equal(false)
    end)
    it("returns nil for a string", function()
        expect(norm.coerce_boolean("yes")).to.equal(nil)
    end)
    it("returns nil for a number", function()
        expect(norm.coerce_boolean(1)).to.equal(nil)
    end)
    it("returns nil for nil input", function()
        expect(norm.coerce_boolean(nil)).to.equal(nil)
    end)
end)

describe("coerce_string", function()
    it("returns the value when it is a non-empty string", function()
        expect(norm.coerce_string("hello")).to.equal("hello")
    end)
    it("returns empty string (pass-through, nonempty check not here)", function()
        expect(norm.coerce_string("")).to.equal("")
    end)
    it("returns nil for a number", function()
        expect(norm.coerce_string(42)).to.equal(nil)
    end)
    it("returns nil for a boolean", function()
        expect(norm.coerce_string(true)).to.equal(nil)
    end)
    it("returns nil for nil input", function()
        expect(norm.coerce_string(nil)).to.equal(nil)
    end)
end)

describe("coerce_number", function()
    it("returns the value when it is an integer", function()
        expect(norm.coerce_number(7)).to.equal(7)
    end)
    it("returns the value when it is a float", function()
        expect(norm.coerce_number(3.14)).to.equal(3.14)
    end)
    it("returns nil for a string", function()
        expect(norm.coerce_number("3")).to.equal(nil)
    end)
    it("returns nil for nil input", function()
        expect(norm.coerce_number(nil)).to.equal(nil)
    end)
end)

describe("coerce_table", function()
    it("returns the value when it is a table", function()
        local t = { a = 1 }
        expect(norm.coerce_table(t)).to.equal(t)
    end)
    it("returns nil for a string", function()
        expect(norm.coerce_table("{}")).to.equal(nil)
    end)
    it("returns nil for nil input", function()
        expect(norm.coerce_table(nil)).to.equal(nil)
    end)
end)

describe("normalize_ctx", function()
    it("leaves required string field intact", function()
        local ctx = { name = "alice" }
        norm.normalize_ctx(ctx, { name = "string" })
        expect(ctx.name).to.equal("alice")
    end)
    it("leaves required number field intact", function()
        local ctx = { count = 5 }
        norm.normalize_ctx(ctx, { count = "number" })
        expect(ctx.count).to.equal(5)
    end)
    it("leaves required boolean field intact", function()
        local ctx = { flag = true }
        norm.normalize_ctx(ctx, { flag = "boolean" })
        expect(ctx.flag).to.equal(true)
    end)
    it("coerces optional field to nil when type mismatches", function()
        local ctx = { label = 99 }  -- number, but spec says string?
        norm.normalize_ctx(ctx, { label = "string?" })
        expect(ctx.label).to.equal(nil)
    end)
    it("returns ctx for chaining", function()
        local ctx = { x = "ok" }
        local ret = norm.normalize_ctx(ctx, { x = "string" })
        expect(ret).to.equal(ctx)
    end)
    it("raises on required string field missing", function()
        local ctx = {}
        local ok, err = pcall(norm.normalize_ctx, ctx, { name = "string" })
        expect(ok).to.equal(false)
        expect(type(err)).to.equal("string")
    end)
    it("raises on required-string empty value", function()
        local ctx = { path = "" }
        local ok, err = pcall(norm.normalize_ctx, ctx, { path = "string" })
        expect(ok).to.equal(false)
        expect(type(err)).to.equal("string")
    end)
    it("raises on unknown tag", function()
        local ctx = { x = "v" }
        local ok, err = pcall(norm.normalize_ctx, ctx, { x = "badtag" })
        expect(ok).to.equal(false)
        expect(type(err)).to.equal("string")
    end)
    it("raises when ctx is not a table", function()
        local ok, err = pcall(norm.normalize_ctx, "not-a-table", {})
        expect(ok).to.equal(false)
        expect(type(err)).to.equal("string")
    end)
end)
